### ISSUE TITLE
DapperMime or pico-debug?

### ISSUE THREAD

**Issue by mfp20** [majbthrd/DapperMime#16]
I tried pico-debug and that's exactly what I need to integrate in my project using a 2nd stage bootloader. Problem is there's no cmake file in that repo. Is BOARD=raspberry_pi_pico DapperMime == pico-debug?

**Comment by majbthrd** [comment]
[TinyUSB](https://github.com/hathach/tinyusb) is a USB stack for multiple USB microcontrollers (including the RP2040).

ARM's sample implementation of CMSIS-DAP is part of [CMSIS_5](https://github.com/ARM-software/CMSIS_5); the implementation includes neither a USB stack nor the platform-specific code to operate the JTAG/SWDIO pins.

[pico-debug](https://github.com/majbthrd/pico-debug) and [DapperMime](https://github.com/majbthrd/DapperMime) are both examples of code that combine TinyUSB, ARM's CMSIS-DAP implementation, and custom platform-specific code.

RaspberryPi's [debugprobe](https://github.com/raspberrypi/debugprobe) is essentially the same idea as DapperMime (they even say "taking inspiration from the DapperMime project"), except the developers at RaspberryPi can't seem to resist making their code proprietary (in this case, by hacking-up ARM's CMSIS-DAP implementation) instead of limiting their changes to the platform-specific code.

There are a number of differences between pico-debug and DapperMime:

1)	pico-debug is specially written to run in the RP2040 RAM; DapperMime is intended to run in flash/ROM on any arbitrary USB microcontroller supported by TinyUSB.
2)	pico-debug uses hardware features unique to the RP2040 to allow one of its cores to debug the other core; DapperMime follows ARM's original vision of CMSIS-DAP where a USB microcontroller is debugging a physically separate ARM.
3)	pico-debug is compiled as a straight C application; DapperMime uses the TinyUSB build scripts
