### ISSUE TITLE
Do not debug RPI PI pico CPU0 with Dappermime running on CPU0 

### ISSUE THREAD

**Issue by UweBonnes** [majbthrd/DapperMime#2]
This is more a hint than an issue.

The RP2040 is the only target using SWD multi-drop and Dappermime the only CMSIS debugger supporting multi-drop I have access too. So I wanted to port the multi-drop changes I did to blackmagic debug probe (BMP) to the BMP CMSIS back-end. 
Testing with Dappermime pins connected to the on-board SWD pins let me get detection up. But as soon  as the debugger tried to attached to CPU 0, Dappermime hanged until poweroff. Trying to fix that, I fixed a lot of other things. After some time I was sure there is a dappermime problem. Until I attached to CPU2 and things worked ;-)

So to make it clear, you can not attach and halt the CPU where the debugger is running on.

Would it be possible to run Dappermime on CPU1 be default? BMP hosted running on the PC has a -t TEST feature to easy see if things are right. To get the memory map, attach is needed. And so a test run without further arguments will hangs  the debugger until power-off. For the principle of least surprise it would be fine if the setup could survive this test ;-)

**Comment by majbthrd** [comment]
Q: Would it be possible to run Dappermime on CPU1?

A: Yes; that is what I already do with pico-debug.  It calls "multicore_launch_core1_raw()", which can be found in multicore.c in pico-sdk.

Note that this means carving out a separate stack for the other core, and then the next problem that you will then create an issue for will be that the code you are running on one core interferes the other because it is controlling the peripherals and PLLs.  My advice is that this is only creating more headaches.

I don't think it is strictly true to say "you can not attach and halt the CPU where the debugger is running on".  I can (and have) used a Segger J-Link to connect to the very core that DapperMime is running on.

However, do you mean that you are trying to use DapperMime to halt its own execution!?  That seems like checking whether an ignition key can stop a car engine whilst driving on a busy highway. ;)

Here is another option that might be worth considering...

DapperMiser can target most (if not all) of CPUs that TinyUSB already has support for (which is quite a few).  I have a STM32F072DISCO example already, and STM32 targets are fairly similar to each other.

You mentioned BluePill in one of your other issues, so I presume that you have one or more.  Have you considered compiling DapperMiser for this?  That would save you the trouble of trying to do everything with one RP2040, and it would let you access both cores on the RP2040 (instead of just one).

If not BluePill, perhaps there are other 3.3V eval boards that you already have that you could use:

https://github.com/hathach/tinyusb/blob/master/docs/boards.md

**Comment by UweBonnes** [comment]
Yes, I mean debugger and debugge on the some chip:
 ./blackmagic -t -n 2
BMP hosted v1.7.1-139-g91677b11
 for ST-Link V2/3, CMSIS_DAP, JLINK and LIBFTDI/MPSSE
Using cafe:4004 123456 TinyUSB
 TinyUSB CMSIS-DAP
Ver 2.0.0, Cap (0x11): SWD, Atomic Cmds, Reportsize 64
Running in Test Mode
...
ROM: Table END
***  1      Raspberry RP2040 M0+
***  2      Raspberry RP2040 M0+
***  3      Raspberry RP2040 Rescue(Attach to reset!) 
Ram   Start: 0x20000000, length   0x40000

Having debugger and debugge on one board keeps wiring lower and encreases the chance to find all needed components. And I will fix the -t Test not to attach to some CPU...

**Comment by majbthrd** [comment]
Trying to use the RP2040 alone is certainly increasing the chance of problems.  I've already spent weeks of time on dealing with running code on one core interfering with the other; it is not a shortcut and not something that you want to volunteer to do.

If you are determined to do this, I've already pointed you to the API call that you need to use, but you are on your own.

Back to using a second board (with any CPU), which I would strongly suggest, it is worth pointing out that there isn't anything particularly unique about DapperMime.  The very name is a deliberate joke that it is a "mime" of ARM's reference code.  If you do a web search for, say, "bluepill cmsis-dap", you'll see lots of examples.  If you have a different board, change the web search.

If the CMSIS-DAP code has a DAP.h with DAP_FW_VER that is "1.2.0" or higher and SW_DP.c has SWD_Sequence(), then it can do multi-drop.

The only thing that makes 2021 DapperMime different from others is that it can target many different CPUs (DAP_Config.h must be created for each one) instead of just one.

**Comment by UweBonnes** [comment]
I have the Bluepill programmed. But missing serial number makes it hard to distinguish the boards!
> ./blackmagic -l
2 debuggers found!
Select with -P <pos>, -s <(partial)serial no.> and/or -S <(partial)description>
 1: 123456, TinyUSB, TinyUSB CMSIS-DAP
 2: 123456, TinyUSB, TinyUSB CMSIS-DAP

Please consider to use the board name  in iProduct and some unique number for the serial. For STM32 I can send you the number generation code used in BMP.

**Comment by majbthrd** [comment]
Please understand that TinyUSB is for many different MCUs.  Some MCUs have no unique ID, and those that do have their own method.  If I add code for STM32, then there will be lots of issues created by people who then complain that it won't compile.

However, you can add it to your local code, and I will show you how.

To add unique IDs to DapperMiser **FOR STM32 ONLY**, replace this in usb_descriptors.c:

```
  if ( index == 0)
  {
    memcpy(&_desc_str[1], string_desc_arr[0], 2);
    chr_count = 1;
  }else
  {
```

with:

```
  if (STRID_LANGID == index)
  {
    memcpy(&_desc_str[1], string_desc_arr[0], 2);
    chr_count = 1;
  else if (STRID_SERIAL == index)
  {
    const uint32_t *idpnt = (uint32_t*)(0x1FFFF7AC); /*DEVICE_ID1*/
    uint32_t tmp;
    for (int digit = 0; digit < 24; digit++)
    {
      if (0 == (digit & 7)) tmp = *idpnt++;
      _desc_str[1+chr_count++] = "0123456789ABCDEF"[tmp & 0xf];
      tmp >>= 4;
    }
  } else
  {

```

**Comment by majbthrd** [comment]
@UweBonnes, FYI: I've added a commit that adds a unique ID for the STM32F072DISCO.  If the board-specific directory has a unique.h, that is used; otherwise, ./bsp/default/unique.h prevails.
