### ISSUE TITLE
JTAG Support

### ISSUE THREAD

**Issue by DatanoiseTV** [majbthrd/DapperMime#7]
It would be nice to see JTAG support coming. I would find it a very useful alternative to the expensive FT2232HL.
Is there a plan to implement it?

**Comment by majbthrd** [comment]
I don't have any immediate plans to do so, but if you wanted to, adding the platform BSP (Board Support Package) code is straightforward(*1) since all the JTAG code is already there.

To do so, go the the ./bsp/xxx of your choice (where xxx is whichever platform you want to compile DapperMime for), open DAP_config.h in a text editor, change "#define DAP_JTAG 0" to "#define DAP_JTAG 1", and fill in the functions PORT_JTAG_SETUP(), PIN_TDI_OUT(), PIN_nTRST_OUT(), and PIN_nRESET_OUT().  You can use the existing PORT_SWD_SETUP() as a guide for PORT_JTAG_SETUP(), and use PIN_SWDIO_OUT() as a guide for the various _OUT().

(*1)Then, you need to document which pins you chose for TDI, nTRST, and nRESET (in addition to the existing TCK/SWCLK and TMS/SWDIO) and why you chose those (and subsequently handle angry users that don't like those pins and who expect you to change the project to suit them)(*2).  You then need to draw diagrams, provide part numbers, and explain how users would connect the target to those chosen pins.  Then you'll need to answer Issues from people like yourself who ask you to do more work for a platform target different from the one that you wrote code for.  Then, for the rest of time, you'll need to field "why doesn't it work" Issues from people who find it easier to post a question than to reason through issues themselves.

(*2)For example, for the rp2040 BSP with DapperMime. I chose the same pinouts (and the exact same picoprobe_config.h file) as Raspberry Pi's proprietary picoprobe project.  I did this because it then conforms to existing RP2040 documentation and makes life easier for users who want to stop using picoprobe and start using something that adopts open source and open standards like CMSIS-DAP that existing multi-platform ARM development software already supports.  @datanoiseTV, you have starred a project called pico-dirtyJtag.  You could adopt those pinouts, but alas, it might be a bad idea because those [pico-dirtyJtag pinouts](https://github.com/phdussud/pico-dirtyJtag) are incompatible with picoprobe (and in turn, DapperMime's existing rp2040 implementation), as the author of pico-dirtyJtag has (like Raspberry Pi did) created something in a vacuum and in this case has chosen arbitrary JTAG pinouts that are incompatible with what others have done before them.
