### ISSUE TITLE
Any plans to support WinUSB ?

### ISSUE THREAD

**Issue by kaidegit** [majbthrd/DapperMime#8]
DAPLink supports both HID and WinUSB . DAPLink in WinUSB mode transfers datas in bulk mode, so transfering speed will be more faster than HID mode.

**Comment by majbthrd** [comment]
No, I do not have any plans.  You are welcome to write it yourself, but here are two reasons why WinUSB mode may NOT make any significant speed improvement:

1) You'll want USB 2.0 High-Speed.  The WinUSB mode was retrofitted to CMSIS-DAP to benefit targets with USB 2.0 High-Speed.  Both the existing Dapper Mime targets (RP2040 and STM32F072) are only USB 1.1 Full-Speed; they do not support USB 2.0 High-Speed.

2) It is strongly desirable to have hardware-acceleration of the SWD/JTAG pins to keep up with faster USB transfers.  There is little value in a fast USB interface when the serial SWD/JTAG interface is CPU-limited due to software bit-bashing of GPIO.
